name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: false
      - run: |
          go mod tidy
          echo GO_SUM_START
          cat go.sum
          echo GO_SUM_END
      - run: go test ./...
